version: '2'

services:
  centos7_php74:
    tty: true
    container_name: centos7.smartybook.docker
    build: centos7_php74
    ports:
      - 5402:80
      - 5403:3306
    volumes:
      - .:/opt/lampp/htdocs:cached
      - ./xampp-linux/lampp/logs:/opt/lampp/logs:cached
