name: setup-ci
description: Set up CI environment (PHP, Node.js, pnpm, Composer)
inputs:
  no_dev:
    description: Run composer with --no-dev
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "7.4"
        # extensions: gd, mbstring はすでに有効になっている
        tools: cs2pr, composer:1.10.28
        ini-values: date.timezone=Asia/Tokyo, memory_limit=-1

    # ----------------------------------------
    # composer install
    # @see https://github.com/actions/starter-workflows/blob/43366bbd1128ba86c37813c92a670eb88f5c50f8/deployments/azure-webapps-php.yml#L53-L70
    # ----------------------------------------
    - name: Get Composer Cache Directory
      id: composer-cache
      shell: bash
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Set up dependency caching for faster installs
      uses: actions/cache@v6
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Run composer install
      shell: bash
      run: |
        composer validate --no-check-publish
        no_dev=()
        if [[ "${{ inputs.no_dev }}" == "true" ]]; then
          no_dev=(--no-dev)
        fi
        composer check-platform-reqs "${no_dev[@]}"
        composer install --prefer-dist --no-progress "${no_dev[@]}"
