name: feature

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review # ドラフト⇨レディに変更したとき

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: github.event.pull_request.draft == false # ドラフトでは実行しない
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - name: setup-ci
        uses: ./.github/actions/setup-ci

      - name: lint
        uses: ./.github/actions/lint

      - name: test
        shell: bash
        run: composer run-script test

  golden-master-test:
    needs: ci # ci ジョブ（lint や test）が PASS した場合のみ実行する
    if: github.event.pull_request.draft == false # ドラフトでは実行しない
    name: Golden Master Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Start Docker Environment
        run: |
          make setup

      - name: Wait for Web Server to be ready
        run: |
          # Web サーバーが応答するまで最大 30 秒待機
          timeout 30s bash -c 'until curl -s -f http://localhost/ > /dev/null 2>&1; do sleep 1; done' || true

      - name: Run Golden Master Tests
        run: |
          make php-test-golden-master

      - name: Setup SSH Debug session
        uses: mxschmitt/action-tmate@v3
        if: failure() # 失敗したときだけ SSH 接続を待機したい場合
        with:
          limit-access-to-actor: true # PR作成者/実行者のみアクセス許可
